name: Example
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    # name: Run spec

    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
    container:
      image: ruby:2.6.4
      env:
        RAILS_ENV: test

    steps:
      - uses: actions/checkout@v1 # https://github.com/actions/checkout/blob/master/action.yml
      - uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundle-${{ hashFiles('**/Gemfile.lock') }}
      - uses: actions/cache@v1
        with:
          path: node_modules
          key: yarn-${{ hashFiles('**/yarn.lock') }}
      - name: Set up yarn and node
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
          curl -sL https://deb.nodesource.com/setup_12.x | bash -
          apt install -y yarn nodejs
      - name: bundle install
        run: |
          gem install bundler
          bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
      # - uses: borales/actions-yarn@v2.0.0
      #   with:
      #     cmd: install
      - name: yarn install
        run: yarn install
      - name: copy database.ci.yml to database.yml
        run: cp -v config/database.ci.yml config/database.yml
      - name: db create
        run: bundle exec rails db:create db:schema:load --trace
      - name: rspec
        run: bundle exec rails rspec