name: Example
on:
  pull_request:
    branches:
    - master

jobs:
  build:
    # name: Run spec

    # ジョブを実行する仮想マシンを選択（ubuntu/macOS/Windows)
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
    container:
      image: ruby:2.6.4

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1 # https://github.com/actions/checkout/blob/master/action.yml
      - name: bundle install
        run: |
          gem install bundler
          bundle install --path vendor/bundle --quiet --jobs 4 --retry 3
      - name: Run tests with ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install
        run: yarn install
      - name: db create
        run: bundle exec rails db:create db:schema:load --trace
      - name: rspec
        run: bundle exec rails rspec